controller_manager:
  ros__parameters:
    update_rate: 100  # Taxa de atualização (100 Hz)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hand_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController # <-- TIPO CORRETO PARA O RQT

hand_position_controller:
  ros__parameters:
    joints:
      - Thumb
      - Index
      - Middle
      - Ring
      - Little
      - Rotate
    # O JointTrajectoryController exige que você declare as interfaces
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity